include: package:effective_dart/analysis_options.yaml

analyzer:
  exclude: ['**/*.mocks.dart']
linter:
  rules:
    avoid_positional_boolean_parameters: false
    avoid_types_on_closure_parameters: false
    prefer_relative_imports: false
    public_member_api_docs: false
    use_setters_to_change_properties: false
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_if_null_operators: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    unnecessary_const: true
    avoid_unnecessary_containers: true
    lines_longer_than_80_chars: false
