name: graphql_mobile
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  effective_dart: 1.3.2
  get_it: 7.2.0
  auto_route: 2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  auto_route_generator: 2.4.1
  build_runner: 2.1.4

flutter:
  uses-material-design: true

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner

scripts:
  g: $clean & $get & $runner build --delete-conflicting-outputs
  gw: $clean & $get & $runner watch --delete-conflicting-outputs
  cg: $clean & $get
